//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Administartor
{
    public int Id { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
}

public partial class ContactUs
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Message { get; set; }
    public System.DateTime CreatedDateTime { get; set; }
}

public partial class DayOfWeek
{
    public int Id { get; set; }
    public string DayOfWeek1 { get; set; }
}

public partial class Expert
{
    public Expert()
    {
        this.Service = new HashSet<Service>();
    }

    public int Id { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string PhoneNumber { get; set; }
    public string Gender { get; set; }
    public System.DateTime DateOfBIrth { get; set; }
    public bool Verified { get; set; }
    public bool Enabled { get; set; }

    public virtual ICollection<Service> Service { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.OrderTimeslot = new HashSet<OrderTimeslot>();
        this.Payment = new HashSet<Payment>();
        this.UserPointTranscation = new HashSet<UserPointTranscation>();
    }

    public int Id { get; set; }
    public int UserId { get; set; }
    public int ServiceId { get; set; }
    public decimal Price { get; set; }
    public string Address { get; set; }
    public System.DateTime ServiceDate { get; set; }
    public bool Enabled { get; set; }
    public System.DateTime CreatedDateTime { get; set; }

    public virtual Service Service { get; set; }
    public virtual User User { get; set; }
    public virtual OrderReview OrderReview { get; set; }
    public virtual ICollection<OrderTimeslot> OrderTimeslot { get; set; }
    public virtual ICollection<Payment> Payment { get; set; }
    public virtual ICollection<UserPointTranscation> UserPointTranscation { get; set; }
}

public partial class OrderReview
{
    public int OrderId { get; set; }
    public int Rating { get; set; }
    public string Reviews { get; set; }
    public System.DateTime CreatedDateTime { get; set; }

    public virtual Order Order { get; set; }
}

public partial class OrderTimeslot
{
    public int OrderID { get; set; }
    public int ServiceId { get; set; }
    public System.DateTime Timeslot { get; set; }

    public virtual Order Order { get; set; }
    public virtual Service Service { get; set; }
}

public partial class OrderView
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int ServiceId { get; set; }
    public decimal Price { get; set; }
    public string Address { get; set; }
    public System.DateTime ServiceDate { get; set; }
    public bool Enabled { get; set; }
    public System.DateTime CreatedDateTime { get; set; }
    public Nullable<int> Rating { get; set; }
    public string UserFullName { get; set; }
    public string ServiceName { get; set; }
    public string ServiceDescription { get; set; }
    public string ExpertFullName { get; set; }
}

public partial class Payment
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public decimal Amount { get; set; }
    public string Method { get; set; }
    public string BillAddress { get; set; }
    public string CardHolderName { get; set; }
    public string CardNumber { get; set; }
    public System.DateTime PaidDateTime { get; set; }

    public virtual Order Order { get; set; }
}

public partial class Service
{
    public Service()
    {
        this.Order = new HashSet<Order>();
        this.OrderTimeslot = new HashSet<OrderTimeslot>();
        this.ServiceTimeslot = new HashSet<ServiceTimeslot>();
    }

    public int Id { get; set; }
    public string Type { get; set; }
    public string Description { get; set; }
    public decimal Price { get; set; }
    public int ExpertId { get; set; }
    public bool Enabled { get; set; }

    public virtual Expert Expert { get; set; }
    public virtual ICollection<Order> Order { get; set; }
    public virtual ICollection<OrderTimeslot> OrderTimeslot { get; set; }
    public virtual ICollection<ServiceTimeslot> ServiceTimeslot { get; set; }
    public virtual ServiceType ServiceType { get; set; }
}

public partial class ServiceTimeslot
{
    public int ServiceId { get; set; }
    public System.TimeSpan Timeslot { get; set; }
    public int DayOfWeek { get; set; }
    public bool Enabled { get; set; }

    public virtual Service Service { get; set; }
}

public partial class ServiceType
{
    public ServiceType()
    {
        this.Service = new HashSet<Service>();
    }

    public string Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<Service> Service { get; set; }
}

public partial class ServiceView
{
    public ServiceView()
    {
        this.Rating = 0m;
    }

    public int Id { get; set; }
    public string TypeId { get; set; }
    public string Description { get; set; }
    public decimal Price { get; set; }
    public int ExpertId { get; set; }
    public string ServiceName { get; set; }
    public string ServiceDescription { get; set; }
    public string ExpertFullName { get; set; }
    public Nullable<decimal> Rating { get; set; }
    public Nullable<int> OrderCount { get; set; }
}

public partial class Timeslot
{
    public System.TimeSpan Timeslot1 { get; set; }
}

public partial class User
{
    public User()
    {
        this.Order = new HashSet<Order>();
        this.UserAddress = new HashSet<UserAddress>();
        this.UserPointTranscation = new HashSet<UserPointTranscation>();
    }

    public int Id { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string PhoneNumber { get; set; }
    public string Gender { get; set; }
    public System.DateTime DateOfBirth { get; set; }
    public bool Enabled { get; set; }

    public virtual ICollection<Order> Order { get; set; }
    public virtual ICollection<UserAddress> UserAddress { get; set; }
    public virtual UserPoint UserPoint { get; set; }
    public virtual ICollection<UserPointTranscation> UserPointTranscation { get; set; }
}

public partial class UserAddress
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public string Address { get; set; }
    public string Postcode { get; set; }

    public virtual User User { get; set; }
}

public partial class UserPoint
{
    public int UserId { get; set; }
    public int Point { get; set; }

    public virtual User User { get; set; }
}

public partial class UserPointTranscation
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public Nullable<int> OrderId { get; set; }
    public int Point { get; set; }
    public System.DateTime DateTime { get; set; }

    public virtual Order Order { get; set; }
    public virtual User User { get; set; }
}

public partial class GetServiceTimeslot_Result
{
    public int ServiceId { get; set; }
    public System.TimeSpan Timeslot { get; set; }
    public int DayOfWeek { get; set; }
    public Nullable<bool> Enabled { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
}
